---
globsettings_workdir: /opt/lorrx
globsettings_user: ''
globsettings_group: ''
globsettings_shell: /usr/bin/zsh

software_copr_repos:
  - quadratech188/vicinae

software_flathub_packages:
  - com.mattjakeman.ExtensionManager

software_dnf_packages:
  - sushi
  - vicinae
  - fzf
  - bat
  - zsh
  - zsh-syntax-highlighting
  - gnome-tweaks
  - sassc
  - glib2-devel
  - ImageMagick
  - dialog
  - optipng
  - inkscape
  - ostree
  - libappstream-glib
  - unzip

extensions_packages:
  - azwallpaper@azwallpaper.gitlab.com
  - blur-my-shell@aunetx
  - dash-to-dock@micxgx.gmail.com
  - user-theme@gnome-shell-extensions.gcampax.github.com
  - tilingshell@ferrarodomenico.com
  - azclock@azclock.gitlab.com
  - vicinae@dagimg-dot
  - burn-my-windows@schneegans.github.com

theme:
  accent: "orange"
  dark: true
  gtk:
    icon: fedora
    hd: true
    darker: true
    name: "WhiteSur"
  cursor: "BreezeX-Dark"
  icon:
    name: "whitesur"
    accent: "orange"
  font:
    name: "JetBrains Mono Regular"
    size: 11

terminal_omz_plugins:
  - name: "zsh-autosuggestions"
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
  - name: "you-should-use"
    repo: "https://github.com/MichaelAquilina/zsh-you-should-use"
  - name: "zsh-bat"
    repo: "https://github.com/fdellwing/zsh-bat"
  - name: "zsh-syntax-highlighting"
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting"

periphery_standard_bindings:
  - key: "/org/gnome/settings-daemon/plugins/media-keys/home"
    binding: '<Super>e'
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-1"
    binding: '<Shift>F1'
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-2"
    binding: '<Shift>F2'
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-3"
    binding: '<Shift>F3'
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-4"
    binding: '<Shift>F4'

periphery_custom_bindings:
  - key: system-monitor
    name: System Monitor
    command: gnome-system-monitor
    binding: '<Shift><Ctrl>Escape'
  - key: vicinae
    name: Vicinae
    command: vicinae toggle
    binding: '<Shift>space'
  - key: terminal
    name: Terminal
    command: ptyxis --new-window
    binding: '<Super>r'
