---
globsettings_workdir: /opt/lorrx
globsettings_user: ''
globsettings_group: ''

software_copr_repos:
  - quadratech188/vicinae

software_dnf_packages:
  - sushi
  - vicinae
  - fzf
  - bat
  - zsh
  - zsh-syntax-highlighting
  - gnome-tweaks

theme:
  cursor: "BreezeX-Dark"
