---
- name: "software | Include repository tasks"
  args:
    apply:
      become: true
  ansible.builtin.include_tasks:
    file: repo.yml

- name: "software | Include package tasks"
  args:
    apply:
      become: true
  ansible.builtin.include_tasks:
    file: pkg.yml
