---
- name: "Set facts for preparation"
  hosts: all
  become: false
  tasks:
    - name: "Set user facts"
      ansible.builtin.set_fact:
        globsettings_user: "{{ ssh_user }}"
        globsettings_group: "{{ ssh_user }}"

    - name: "User facts"
      ansible.builtin.debug:
        msg: "User facts set: user={{ globsettings_user }}, group={{ globsettings_group }}"

- name: "Install required software on Fedora Workstation as root"
  hosts: all
  become: true
  roles:
    - globsettings
    - software
