---
- name: "Set facts for preparation"
  hosts: all
  become: false
  connection: local
  vars:
    file_test: "{{ lookup('ansible.builtin.file', 'roles/desktop/files/tilingshell-layouts.json') }}"
  tasks:

    - debug:
        var: file_test

