---
- name: "desktop | Configure workspace settings"
  ansible.builtin.include_tasks:
    file: workspaces.yml

- name: "desktop | Enable and start Vicinae"
  ansible.builtin.include_tasks:
    file: vicinae.yml
