---
- name: "desktop | Configure workspace settings"
  ansible.builtin.include_tasks:
    file: workspaces.yml

- name: "desktop | Configure windows settings"
  ansible.builtin.include_tasks:
    file: windows.yml

- name: "desktop | Enable and start Vicinae"
  ansible.builtin.include_tasks:
    file: vicinae.yml

- name: "desktop | Configure wallpaper"
  ansible.builtin.include_tasks:
    file: wallpaper.yml

- name: "desktop | Configure shell settings"
  ansible.builtin.include_tasks:
    file: shell.yml

- name: "desktop | Configure tilingshell settings"
  ansible.builtin.include_tasks:
    file: tilingshell.yml

- name: "desktop | Configure dock settings"
  ansible.builtin.include_tasks:
    file: dock.yml
