---
- name: "desktop | workspaces | Configure fixed number of workspaces"
  community.general.dconf:
    key: "{{ desktop_workspaces_setting.key }}"
    value: "{{ desktop_workspaces_setting.value }}"
  loop:
    - { key: "/org/gnome/mutter/dynamic-workspaces", value: "{{ desktop_dynamic_workspaces }}" }
    - { key: "/org/gnome/desktop/wm/preferences/num-workspaces", value: "{{ desktop_workspaces }}" }
    - { key: "/org/gnome/mutter/workspaces-only-on-primary", value: "{{ desktop_workspaces_only_on_primary }}" }
  loop_control:
    loop_var: desktop_workspaces_setting
