desktop_dock_base_dconf_key: "/org/gnome/shell/extensions/dash-to-dock"
desktop_dock_settings:
  - key: "{{ desktop_dock_base_dconf_key }}/desktop_shell_settings"
    value: "32"
  - key: "{{ desktop_dock_base_dconf_key }}/show-show-apps-button"
    value: "false"
  - key: "{{ desktop_dock_base_dconf_key }}/show-trash"
    value: "false"
  - key: "{{ desktop_dock_base_dconf_key }}/show-mounts"
    value: "false"
  - key: "{{ desktop_dock_base_dconf_key }}/show-mounts-only-mounted"
    value: "false"
  - key: "{{ desktop_dock_base_dconf_key }}/running-indicator-style"
    value: "'DOTS'"
  - key: "{{ desktop_dock_base_dconf_key }}/custom-background-color"
    value: "true"
  - key: "{{ desktop_dock_base_dconf_key }}/background-color"
    value: "'rgb(17,17,17)'"
  - key: "{{ desktop_dock_base_dconf_key }}/transparency-mode"
    value: "'FIXED'"
  - key: "{{ desktop_dock_base_dconf_key }}/background-opacity"
    value: "0.5"
