---
desktop_tilingshell_base_dconf_key: "/org/gnome/shell/extensions/tilingshell"
desktop_tilingshell_settings:
  - key: "{{ desktop_tilingshell_base_dconf_key }}/cycle-layouts-backward"
    value: "['<Shift>']"
  - key: "{{ desktop_tilingshell_base_dconf_key }}/edge-tiling-mode"
    value: "'default'"
  - key: "{{ desktop_tilingshell_base_dconf_key }}/enable-autotiling"
    value: "false"
  - key: "{{ desktop_tilingshell_base_dconf_key }}/enable-blur-selected-tilepreview"
    value: "true"
  - key: "{{ desktop_tilingshell_base_dconf_key }}/enable-blur-snap-assistant"
    value: "true"
  - key: "{{ desktop_tilingshell_base_dconf_key }}/enable-snap-assist"
    value: "true"
  - key: "{{ desktop_tilingshell_base_dconf_key }}/enable-window-border"
    value: "false"
  - key: "{{ desktop_tilingshell_base_dconf_key }}/selected-layouts"
    value: "[['Layout 1', 'Layout 1'], ['Layout 1', 'Layout 1'], ['Layout 1', 'Layout 1'], ['Layout 1', 'Layout 1']]"
  - key: "{{ desktop_tilingshell_base_dconf_key }}/show-indicator"
    value: "false"
  - key: "{{ desktop_tilingshell_base_dconf_key }}/window-use-custom-border-color"
    value: "false"
  - key: "{{ desktop_tilingshell_base_dconf_key }}/layouts-json"
    value: "'{{ lookup('ansible.builtin.file', 'files/tilingshell-layouts.json') }}'"
