---
desktop_dynamic_workspaces: "false"
desktop_workspaces: "4"
desktop_workspaces_only_on_primary: "false"
desktop_wallpaper_directory: "{{ ansible_facts['env']['HOME'] }}/.local/share/wallpaper"
desktop_wallpaper_duration: "(0, 30, 0)"
