---
- name: Get installed GNOME Shell major version
  ansible.builtin.command: gnome-shell --version
  register: extensions_gnome_version_raw
  changed_when: false

- name: Extract major GNOME version
  ansible.builtin.set_fact:
    gnome_major_version: "{{ extensions_gnome_version_raw.stdout | regex_search('GNOME Shell ([0-9]+)', '\\1') | first }}"

- name: "extensions | Ensure GNOME extension folder exists"
  ansible.builtin.file:
    path: "~/.local/share/gnome-shell/extensions/{{ extensions_item }}"
    mode: '0755'
    state: directory
  loop: "{{ extensions_packages }}"
  loop_control:
    loop_var: extensions_item

- name: "extensions | Get extension details form GNOME API"
  ansible.builtin.uri:
    url: "https://extensions.gnome.org/extension-info/?uuid={{ extensions_info_item }}&shell_version={{ gnome_major_version }}"
    return_content: true
  register: extensions_info
  loop: "{{ extensions_packages }}"
  loop_control:
    loop_var: extensions_info_item

- debug:
    var: extensions_info

- name: "extensions | Download and unarchive GNOME extensions"
  ansible.builtin.unarchive:
    src: "https://extensions.gnome.org/{{ extensions_unzip_item.download_url }}"
    dest: "~/.local/share/gnome-shell/extensions/{{ extensions_unzip_item.uuid }}"
    remote_src: true
  loop: "{{ extensions_info.results }}"
  loop_control:
    loop_var: extensions_unzip_item
  when: extensions_unzip_item.download_url is defined

- name: "extensions | Enable GNOME extensions"
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "{{ extensions_packages | list | to_json }}"
