---
- name: "keyboard | bindings | Configure standard GNOME bindings"
  community.general.dconf:
    key: "{{ keyboad_binding.key }}"
    value: "['{{ keyboad_binding.binding }}']"
    state: present
  loop: "{{ keyboard_standard_bindings }}"
  loop_control:
    loop_var: keyboad_binding

- name: "keyboard | bindings | Register custom keybinding list for custom shortcuts"
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ keyboad_custom_binding.key }}/']"
    state: present
  loop: "{{ keyboard_custom_bindings }}"
  loop_control:
    loop_var: keyboad_custom_binding

- name: "keyboard | bindings | Configure custom keybinding name"
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ keyboad_custom_binding_name.key }}/name"
    value: "'{{ keyboad_custom_binding_name.name }}'"
    state: present
  loop: "{{ keyboard_custom_bindings }}"
  loop_control:
    loop_var: keyboad_custom_binding_name

- name: "keyboard | bindings | Configure custom keybinding command"
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ keyboad_custom_binding_cmd.key }}/command"
    value: "'{{ keyboad_custom_binding_cmd.command }}'"
    state: present
  loop: "{{ keyboard_custom_bindings }}"
  loop_control:
    loop_var: keyboad_custom_binding_cmd

- name: "keyboard | bindings | Configure custom keybinding binding"
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ keyboad_custom_binding_bind.key }}/binding"
    value: "'{{ keyboad_custom_binding_bind.binding }}'"
    state: present
  loop: "{{ keyboard_custom_bindings }}"
  loop_control:
    loop_var: keyboad_custom_binding_bind
